### PR TITLE
Server side uploads improvements

### PR DESCRIPTION
**Pull request by dazza-dev**
- Added function to delete files on the server
- Renamed the "removeFile" event to "fileRemoved"
- New emit event: "fileUploaded"
- Readme improvements

### CODE REVIEW

**Comment by JaxThePrime** [comment]
@dazza-dev Hi my friend appreciate your contribution to the project. i was wondering if you'd like to add the new features and edited features of the project to the preview site as well, im currently very busy i couldn't do it myself i you are intrested let me know so i can add you in the repo.

Best regards

**Comment by dazza-dev** [comment]
Hi @JaxThePrime Sure, I'd be happy to help with this.

**Comment by JaxThePrime** [comment]
@dazza-dev Great ! can you please give me your email for gitlab

**Comment by dazza-dev** [comment]
adaza90@outlook.com

**Pull request merged**
